{"uuid": "5074934e-9d78-4088-b74e-92f935063196", "children": ["012eac5f-0db9-4a0b-8a1d-f8c8480dec35", "e72c98eb-61ca-41b1-a274-d6c80e913702", "6748adb5-79c5-4564-ae8d-bbbf25d52b1a"], "befores": [{"name": "_Class__pytest_setup_class", "status": "broken", "statusDetails": {"message": "AttributeError: type object 'Test_Login_Vue' has no attribute 'log'\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/yangzhiqi/PycharmProjects/Selenium/venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/yangzhiqi/PycharmProjects/Selenium/venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"/Users/yangzhiqi/PycharmProjects/Selenium/venv/lib/python3.9/site-packages/_pytest/python.py\", line 701, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"/Users/yangzhiqi/PycharmProjects/Selenium/venv/lib/python3.9/site-packages/_pytest/python.py\", line 632, in _call_with_optional_argument\n    func(arg)\n  File \"/Users/yangzhiqi/PycharmProjects/Selenium/TestCase/test_vue.py\", line 22, in setup_class\n    self.log.info(\"======打开浏览器======\")  # 加入log\n"}, "start": 1647428595468, "stop": 1647428595468}], "start": 1647428595468, "stop": 1647428595566}